/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aleatgames01;

import javax.swing.JLabel;

/**
 *
 * @author CESAR
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    //static String resultado[] = new String[9];
    //static int p = 0;
    public Main() {
        initComponents();
    }

   /* public static void agregar(String valor){
        resultado[p] = valor;
        System.out.println("result: ["+p+"]--"+resultado[p]);
        p++;
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabe7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        buttonIniciar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButtonLanzar = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabelDado1 = new javax.swing.JLabel();
        jLabelDado2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(10, 10, 10));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aleatgames01/resources/item1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aleatgames01/resources/item1.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, -1, -1));

        jLabe7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aleatgames01/resources/item1.png"))); // NOI18N
        jPanel1.add(jLabe7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aleatgames01/resources/item2.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aleatgames01/resources/item2.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aleatgames01/resources/item2.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aleatgames01/resources/item3.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aleatgames01/resources/item3.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aleatgames01/resources/item3.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aleatgames01/resources/barra1.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, 320, 10));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 90, -1));

        buttonIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aleatgames01/resources/boton.jpg"))); // NOI18N
        buttonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIniciarActionPerformed(evt);
            }
        });
        jPanel1.add(buttonIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, 120, 120));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aleatgames01/resources/barra2.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, -1, 10));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aleatgames01/resources/barraverti1.png"))); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 10, 320));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aleatgames01/resources/barraverti2.png"))); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 10, 310));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aleatgames01/resources/barraverti2.png"))); // NOI18N
        jLabel14.setText("jLabel14");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 10, 260));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aleatgames01/resources/barra5.png"))); // NOI18N
        jLabel15.setText("jLabel15");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 370, 10));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aleatgames01/resources/barra2.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 310, 10));

        jButtonLanzar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aleatgames01/resources/Dados.png"))); // NOI18N
        jButtonLanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLanzarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLanzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 170, 80));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aleatgames01/resources/Casino1.PNG"))); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 440, 150));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aleatgames01/resources/CartasNeo.PNG"))); // NOI18N
        jLabel18.setText("jLabel18");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, -1, -1));

        jLabelDado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aleatgames01/dado1.png"))); // NOI18N
        jPanel1.add(jLabelDado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabelDado2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aleatgames01/dado6.png"))); // NOI18N
        jPanel1.add(jLabelDado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIniciarActionPerformed
        // TODO add your handling code here:
        JLabel vImages1[] = { jLabel1,  jLabel2,  jLabel3};
      
        ThreadManageTragaMoneda item1 = new ThreadManageTragaMoneda(vImages1);
        item1.start();
        
        JLabel vImages2[] = { jLabel4,  jLabel5,  jLabel6};
      
        ThreadManageTragaMoneda item2 = new ThreadManageTragaMoneda(vImages2);
        item2.start();
         JLabel vImages3[] = { jLabe7,  jLabel8,  jLabel9};
      
        ThreadManageTragaMoneda item3 = new ThreadManageTragaMoneda(vImages3);
        item3.start();
       // jLayeredPane1.add(testlabel,100);
      
    }//GEN-LAST:event_buttonIniciarActionPerformed

    private void jButtonLanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLanzarActionPerformed
        // TODO add your handling code here:
        ThreadManage tt = new ThreadManage(jLabelDado1);
        tt.start();
        ThreadManage tt2 = new ThreadManage(jLabelDado2);
        tt2.start();
    }//GEN-LAST:event_jButtonLanzarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonIniciar;
    private javax.swing.JButton jButtonLanzar;
    private javax.swing.JLabel jLabe7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDado1;
    private javax.swing.JLabel jLabelDado2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    
}





